before install:
 - echo 'yes' | sudo add-apt-repository ppa:chris-lea/zeromq
 - sudo apt-get update
 - sudo apt-get install libzmq-dev libpgm-dev
 - sudo dpkg -i debs/jzmq_2.1.0-1_i386.deb

language: java

script: mvn test

jdk:
 - openjdk6
 - openjdk7
